version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: festmyd-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    networks:
      - festmyd-network

networks:
  festmyd-network:
    driver: bridge